In [2]:
# 1. Write a Python Program to Add Two Matrices?
import numpy as np
matrix1=np.array([[1,2,3,4],
                  [2,3,4,5]])
matrix2=np.array([[1,2,3,4],
                  [2,3,4,5]])
print(matrix1+matrix2)

[[ 2  4  6  8]
 [ 4  6  8 10]]


In [4]:
# 2. Write a Python Program to Multiply Two Matrices?
import numpy as np
matrix1=np.array([[1,2,3,4],
                  [2,3,4,5]])
matrix2=np.array([[1,2,3,4],
                  [2,3,4,5]])
print(matrix1*matrix2)

[[ 1  4  9 16]
 [ 4  9 16 25]]


In [7]:
# 3. Write a Python Program to Transpose a Matrix?
import numpy as np
matrix=np.array([[1,2,3,4],
                  [2,3,4,5]])
print(matrix.T)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [45]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?
Order='shashi is joined in ineuron'
l=Order.split()
l.sort()
" ".join(l)


'in ineuron is joined shashi'

In [48]:
# 5. Write a Python Program to Remove Punctuation From a String?
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
original_string=input("enter a string")
string=" "
for i in original_string:
    if i not in punctuations:
        string+=i
print(string)

enter a stringshashi@@#$@#$ ad72
 shashi ad72
